import {MantineProvider} from '@mantine/core';
import {Nav} from "@/libs/ui/nav/Nav";

import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import '@mantine/core/styles.css';
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import type { Viewport } from 'next'
import Providers from "@/app/providers";

export const viewport: Viewport = {
  themeColor: '#FFF',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
          className={`antialiased`}
        >
          <MantineProvider>
            <Providers>
              <Nav />

              {children}
            </Providers>
          </MantineProvider>
        </body>
    </html>
  );
}
